apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: cicada-operator-account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: cicada-engine-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicada-operator-role
rules:
  # Kopf framework
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # Cicada objects
  - apiGroups: [cicada.io]
    resources: [testengines]
    verbs: [list, watch, patch]
  - apiGroups: [""]
    resources: [pod, pods, services]
    verbs: [get, list, create, delete, deletecollection]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cicada-engine-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "delete", "deletecollection", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicada-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicada-operator-role
subjects:
  - kind: ServiceAccount
    name: cicada-operator-account
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicada-engine-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicada-engine-role
subjects:
- kind: ServiceAccount
  name: cicada-engine-account
  namespace: default